### ISSUE TITLE
Lua build options don't work.

### ISSUE THREAD

**Issue by jpeach** [circonus-labs/libmtev#176]
The `--enable-lua` configuration option is allowed to take `no`, `lua52` or `LuaJIT` as options.

If you pass `--disable-lua`, the build still tries to build the various Lua components. It is clear that no-one ever does this.

If you pass `--enable-lua=lua52`, you get an [unconditional error](https://github.com/circonus-labs/libmtev/blob/master/configure.in#L256).

If you pass `--enable-lua=LuaJIT`, you need an undocumented dependency on the `udns-devel` package (at least on Fedora).

What's the right approach here? Enforce that LuaJIT is required? Try to make Lua optional? Support multiple different Lua implementations?

**Comment by postwait** [comment]
It should be workable without Lua, but lua52 is fruitless. I think we should allow "no" and "luajit"

**Comment by jpeach** [comment]
That makes sense. I added this change to #175.
